version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Add other environment variables as needed
      # - DATABASE_URL=postgresql://postgres:password@db:5432/mydb
    restart: unless-stopped
    # If you need to connect to other services, uncomment the following:
    # depends_on:
    #   - db

  # Uncomment the following section if you need a database
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=mydb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# Uncomment if using the database service
# volumes:
#   postgres_data: 